version: '3'
services:
  db_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: taximus
      POSTGRES_DB: taxmax
      # POSTGRES_PASSWORD: assign during production
    logging:
      driver: none
    restart: "always"
    ulimits:
      nproc: 500
      nofile:
        soft: 2048
        hard: 4096
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-mac
    # environment:
      # - NODE_ENV=production  # set this in production
    ports:
      - "8080:8080"
    links:
      - db_postgres
    restart: "always"
    ulimits:
      nproc: 500
      nofile:
        soft: 2048
        hard: 4096
