version: '3'
services:
  # db_postgres:
  #   image: postgres:11
  #   environment:
  #     POSTGRES_USER: mentorq-api
  #     POSTGRES_DB: mentorq
  #   logging:
  #     driver: none
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    # links:
    #   - db_postgres
