version: '3'
services:
  db_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: taximus
      POSTGRES_DB: taxmax
      POSTGRES_PASSWORD: 'gMb3jENs2ldXMNOVLFoZe4ON9OFMNqsUqiNi6iCzy'
    logging:
      driver: none
    restart: "always"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - db_postgres
    restart: "always"
    volumes:
      - ./access.log:/var/log/taxmax.log
